### ISSUE TITLE
有道精品课找不到

### ISSUE THREAD

**Issue by binfeng1223** [shichunlei/flutter_app#14]

**Comment by binfeng1223** [comment]
有道精品课找不到，麻烦帮我处理一下

**Comment by shichunlei** [comment]
apk上传的不是最新版本，所以还没有，你可以把代码运行一下，新的APK我会马上更新的，具体代码就在   lib 下的 youdao 包下啊，入口在 “5 功能” 下的 ‘有道精品课’ 。
