### ISSUE TITLE
iconfont.ttf 这个图标库在哪里下载的呀？

### ISSUE THREAD

**Issue by HyggeBo7** [shichunlei/flutter_app#15]
iconfont.ttf 这个图标库在哪里下载的呀？

**Comment by shichunlei** [comment]
[阿里巴巴矢量图标库](https://www.iconfont.cn/)

具体怎么使用网上有好多文章介绍
[flutter 引入第三方 Icon 图标（以阿里图标库为例)](https://blog.csdn.net/shuaizi96/article/details/88550217)
