### ISSUE TITLE
你好, 请教一个瀑布流相关的东西

### ISSUE THREAD

**Issue by YeFei572** [shichunlei/flutter_app#2]
看到项目中使用了瀑布流插件`flutter_staggered_grid_view: ^0.2.7`

我最近也用到了这个插件, 想问一下如果是如下图所示该如何布局?
是将整个首页放在一个listView里面还是怎么做的? 还请作者点拨一下.
![image](https://user-images.githubusercontent.com/26360338/57665802-f8218e80-762f-11e9-807f-51810438cf59.png)

**Comment by shichunlei** [comment]
[点击这里](https://github.com/shichunlei/flutter_app/blob/master/lib/widget/sliver.dart)

我简单地写了一个demo，你看一下是否你想要的效果

**Comment by YeFei572** [comment]
多谢作者, 我试试看

**Comment by YeFei572** [comment]
首先谢谢作者的特意编写,感激涕零, 搞了好几天没搞出来,我之前一直用`NestedScrollView`而没有采用`CustomScrollView`, 感觉自己掉坑里了.
 作者的方法完全可以解决我的困惑, 只是有一个问题: 我项目里使用的`appBar`是渐变色, 当页面滑到顶部的时候,整个`appBar`是透明的, `appBar`中的搜索框有个轮廓, 然后等向下滑的时候`appBar`的颜色会慢慢的变成主题色,搜索框轮廓不做任何改变,
 我之前使用`NestedScrollView`实现了该效果, 如今换成`CustomScrollView`后就有点架不住了, 因为对这个组件不太熟悉, 所以看作者是否有空帮忙解惑一二. 万分感激!

**Comment by shichunlei** [comment]
可以使用ScrollController监听CustomScrollView的滑动距离判断显示透明的appbar还是渐变非透明的apbar。[代码见](https://github.com/shichunlei/flutter_app/blob/master/lib/widget/sliver.dart)

没有太看懂你的表述，但是大概应该是我理解的那样。不知道你表达的是不是我实现的这样

**Comment by YeFei572** [comment]
非常感谢作者的回复, 认真的看了作者的实现方式, 采用的是监控滑动条的位置来改变`appBar`的颜色

我这边这种方式主要是为了不会遮挡banner, 所以做成透明的AppBar, 作者这种实现方式可以满足要求, 只是产品那边意思不是这样的, 可能我没有表达清楚自己的意思, 我的意思是透明渐变成主题色, 不是appbar最后是渐变色, 这怪我表达能力不好, 为此我找了一张图片, 还请作者看上一眼, 这种方式我觉得就是动画了 ,完完全全是动画, 不知道作者怎么看呢?
![登录](https://user-images.githubusercontent.com/26360338/57771609-c39ff680-7745-11e9-87e8-098e0feac14f.gif)

**Comment by shichunlei** [comment]
根据监听页面滑动距离算出透明度navAlpha，然后根据需求随着滑动利用navAlpha改变标题栏的颜色（此处颜色使用ARGB格式）示例中我使用的是随着滑动标题栏背景有透明逐渐变为白色，搜索框边框颜色、左右图标颜色由白色变为黑色（[见代码](https://github.com/shichunlei/flutter_app/blob/master/lib/xianyu/home.dart)），你可已根据你项目中需求变为你项目中的主题色（将你的主题色变换为ARGB格式）

其实我在demo里多出用到了标题栏随着滑动渐变变化的例子
[仿朋友圈](https://github.com/shichunlei/flutter_app/blob/master/lib/wechat_friends/page/wechat_friends_circle.dart)

[百姓生活首页](https://github.com/shichunlei/flutter_app/blob/master/lib/baixing_life/page/home.dart)

[百姓生活会员页](https://github.com/shichunlei/flutter_app/blob/master/lib/baixing_life/page/member.dart)

[天气](https://github.com/shichunlei/flutter_app/blob/master/lib/weather/page/weather_page.dart)

**Comment by YeFei572** [comment]
好的, 去看一下, 多谢作者哈!

**Comment by YeFei572** [comment]
感谢作者, 已经搞定了!

想请教一下作者, 不知道作者接触flutter有多久, 感觉你的flutter相关知识面很广泛啊, 我接触flutter一个月, 你谈的东西我很多都不知道, 想问一下有没有什么学习计划方案指点一二.

**Comment by shichunlei** [comment]
我也是过了年之后大概有三四个月了吧，才开始接触Flutter的，我开始也是主要看别人的项目代码（不一定是完整项目，一开始我也看不太懂那些复杂的项目）跟着敲但是不要完全按照源代码敲（Flutter既然一切皆组件，肯定不是只有一种组件可以完成某个需求的），然后看一些大神些的博客，别人总结的一些技巧。主要是大量的练习。平时在掘金（有个flutter板块，在android下面）、简书、github等等上面看到一些好的自定义组件或者效果就会记录到我这个Demo上，慢慢总结，熟能生巧。

方便的话可以加一下我微信：18601952581     或者QQ：1558053958    可以方便交流经验。

**Comment by YeFei572** [comment]
荣幸之至啊
