### ISSUE TITLE
无法运行啊

### ISSUE THREAD

**Issue by hlj2722** [shichunlei/flutter_app#4]
运行环境为
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.437], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (version 2.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.34.0)
[√] VS Code, 64-bit edition (version 1.26.1)
[√] Connected device (2 available)

! Doctor found issues in 2 categories.

--------------------------------------------------------------------------
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\2.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\3.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\4.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\5.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\6.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\7.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\8.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\9.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\10.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\11.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\12.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\13.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\14.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\15.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\16.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\17.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\18.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\19.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\20.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\21.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\22.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\23.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\24.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\25.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\26.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\27.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\28.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\29.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\30.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\31.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\32.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\33.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\34.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\35.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\36.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\37.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\38.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\39.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\40.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\41.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\42.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\43.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\44.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\45.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\46.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\47.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\48.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\49.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\50.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\51.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\52.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\53.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\54.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\55.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\56.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\57.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\58.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\59.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\60.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\61.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\62.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\63.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\64.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\65.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\66.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\67.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\68.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\69.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\70.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\71.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\72.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\73.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\74.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\75.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\76.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\77.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\78.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\79.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\80.jar, D:\flutter_app\flutter_app_shichunlei\build\app\intermediates\transforms\dexBuilder\debug\81.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.app.INotificationSideChannel

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by lancelot9527** [comment]
Flutter 1.5.4 hotfix.2 一样跑步起来。
```
fatal error: 'multi_image_picker/multi_image_picker-Swift.h' file not found
    #import <multi_image_picker/multi_image_picker-Swift.h>
```

**Comment by macroswang** [comment]
你这项目完全无法跑起来

**Comment by shichunlei** [comment]
> Flutter 1.5.4 hotfix.2 一样跑步起来。
> 
> ```
> fatal error: 'multi_image_picker/multi_image_picker-Swift.h' file not found
>     #import <multi_image_picker/multi_image_picker-Swift.h>
> ```

你看一下[multi_image_picker](https://github.com/Sh1d0w/multi_image_picker)这个包的配置

**Comment by lancelot9527** [comment]
> > Flutter 1.5.4 hotfix.2 一样跑步起来。
> > ```
> > fatal error: 'multi_image_picker/multi_image_picker-Swift.h' file not found
> >     #import <multi_image_picker/multi_image_picker-Swift.h>
> > ```
> 
> 你看一下[multi_image_picker](https://github.com/Sh1d0w/multi_image_picker)这个包的配置

multi_image_picker: 2.4.11。直接clone你的项目，其实是报pickerColor什么的没有声明，inner_drawer 和 setting 文件。

**Comment by macroswang** [comment]
我这儿已经跑起来了。但是ColorPicker会无法识别，我暂时屏蔽了这段代码
@lancelot9527 我修改的地方如下:
1、在podfile中加入：
    target 'Runner' do
        use_frameworks! # <— 加入这句
   
#加入下面一段
  pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    Pod::Installer::Xcode::TargetValidator.send(:define_method, 
   :verify_no_static_framework_transitive_dependencies) {}
  end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '4.2'  #加了这句
    end
  end
end

如果还会报错。在IOS工程中的build  Settings 中的 Compile Sources As 修改为
Objective-C++
 
上面就是我修改的所有地方。希望对你有帮助

**Comment by lancelot9527** [comment]
> 我这儿已经跑起来了。但是ColorPicker会无法识别，我暂时屏蔽了这段代码
> @lancelot9527 我修改的地方如下:
> 1、在podfile中加入：
> target 'Runner' do
> use_frameworks! # <— 加入这句
> 
> #加入下面一段
> pre_install do |installer|
> # workaround for [CocoaPods/CocoaPods#3289](https://github.com/CocoaPods/CocoaPods/issues/3289)
> Pod::Installer::Xcode::TargetValidator.send(:define_method,
> :verify_no_static_framework_transitive_dependencies) {}
> end
> 
> post_install do |installer|
> installer.pods_project.targets.each do |target|
> target.build_configurations.each do |config|
> config.build_settings['ENABLE_BITCODE'] = 'NO'
> config.build_settings['SWIFT_VERSION'] = '4.2' #加了这句
> end
> end
> end
> 
> 如果还会报错。在IOS工程中的build Settings 中的 Compile Sources As 修改为
> Objective-C++
> 
> 上面就是我修改的所有地方。希望对你有帮助

蟹蟹
