### ISSUE TITLE
下载的2.0 在flutter2.2.0版本里启动，报错。新手求答案

### ISSUE THREAD

**Issue by songpangyu** [shichunlei/flutter_app#40]
![image](https://user-images.githubusercontent.com/27877590/126937035-e0ae0515-139e-4d30-96d7-92a88a3ff4b6.png)

**Comment by ahthabc** [comment]
flutter_colorpicker 试试0.4.0版本的！我是把相关的屏蔽掉了！在flutter_colorpicker  issues 中其他人也预到类似问题，切换到0.4.0版本就没有问题了

**Comment by songpangyu** [comment]
> flutter_colorpicker 试试0.4.0版本的！我是把相关的屏蔽掉了！在flutter_colorpicker issues 中其他人也预到类似问题，切换到0.4.0版本就没有问题了

是的，我也是自己试出来 用0.4.0版本搞定了。  感谢你正确的回复。
